export const LOAD_QUESTIONS = "LOAD_QUESTIONS";
export const LOAD_QUESTIONS_SUCCESS = "LOAD_QUESTIONS_SUCCESS";
export const LOAD_QUESTIONS_FAILED = "LOAD_QUESTIONS_FAILED";
export const CLICK_RECORD_BUTTON = "CLICK_RECORD_BUTTON";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const ASK_QUESTION = "ASK_QUESTION";
export const GET_CURRENT_QUESTION ="GET_CURRENT_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";